### ISSUE TITLE
connect the micro：bit

### ISSUE THREAD

**Issue by xiaolongchengithub** [thegecko/microbit-web-bluetooth#1]
bluetooth = require("microbit-web-bluetooth")
let led = bluetooth.requestMicrobit("BBC micro:bit[vutag]")

i do not konow why i can not connect my micro:bit

**Comment by thegecko** [comment]
`requestMicrobit` is an asynchronous function, either handle the promise it returns or use async/await

**Comment by thegecko** [comment]
Closing due to no comments, please reopen if issue persists
