### ISSUE TITLE
[QUESTION] Does this work with the latest "official" firmware?

### ISSUE THREAD

**Issue by ziriax** [thegecko/microbit-web-bluetooth#18]
First of all thanks for this great library!

As of today (20 april 2021), does this need a special firmware, or does https://microbit.org/get-started/user-guide/firmware work out of the box?

Thanks a lot,
Peter

**Comment by thegecko** [comment]
Unlikely I'm afraid, the bluetooth stack security needs setting up in a specific way. See the docs for more info:

https://thegecko.github.io/microbit-web-bluetooth/docs/index.html

Some prebuilt binaries which work can be seen here:

https://github.com/thegecko/microbit-web-bluetooth/tree/master/hex

**Comment by ziriax** [comment]
Thanks for the info. I was looking for the source code of this custom firmware, but couldn't find it. The docs mention it is based on the codal examples, but the link in the doc (https://github.com/microbit-foundation/codal) is dead. Is this link (https://github.com/microbit-foundation/codal-microbit-nrf5sdk) the correct one?

**Comment by carlosperate** [comment]
This is the current repo to create CODAL projects for the micro:bit: https://github.com/lancaster-university/microbit-v2-samples/
