### ISSUE TITLE
Test implementation of IO Pin Service

### ISSUE THREAD

**Issue by thegecko** [thegecko/microbit-web-bluetooth#2]
Implement IO Pin Service:
- [ ] Pin Data
- [ ] Pin Data Changed Event
- [ ] Pin AD Configuration
- [ ] Pin IO Configuration
- [ ] PWM Control

**Comment by benmoran** [comment]
I have been experimenting with controlling a pair of continuous rotation servos using the Bluetooth IO Pin service (from Chromium, on Ubuntu Linux).  These need PWM output.

After the small change in https://github.com/thegecko/microbit-web-bluetooth/pull/12 the setPwmControl() call seems to be working properly.

So for instance `setPwmControl({pin:0, value:128, period:20000})` sets up Pin 0 to output a pulse-width modulated cycle with a period of 20,000 microseconds (20ms) and a duty cycle of (128/1024)*20000 = 2.5ms . (In my case, that's the signal for my servos to rotate full speed forwards.  A duty cycle of 0.5ms, corresponding to `value:26` makes them rotate full speed backward.)

I haven't needed to use the other calls, and I'm not sure how to test them, but from what I can see they are also basically doing the right thing in general.  From a grep through the code the byte order looks to be set correctly elsewhere.

**Comment by thegecko** [comment]
Awesome feedback @benmoran I'm going to close this issue, thanks!
