### ISSUE TITLE
Need static pure js microbit-web-bluetooth lib

### ISSUE THREAD

**Issue by VlasovAlexey** [thegecko/microbit-web-bluetooth#39]
First, thank you for a great and documented library! Works great on the web server. But I'm having trouble using it as regular pure js for the WebView App. In my project it writes an error:

Access to script at ‘file:///H:/DiveProMeSTONE/web_component_src/microbit.esm.js’ from origin ‘null’ has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.

The reason of the error is clear. Launching without a web server is not possible because modules are used and calls will be a file.  Your example works fine on my server, but there are so many files:
barebones.css
index.html
microbit.js
microbit.esm.js
p-0x0t5gtj.entry.js
p-416d80af.js
p-7yjqh0pg.entry.js
p-9qcccxgd.entry.js
p-benpzh9n.entry.js
p-bn6rxqqj9.entry.js
p-bny9jj1c.entry.js
p-cbi1lxba.entry.js
p-drb32voq.entry.js
p-e1gjaezr.entry.js
p-ede9ed58.js
p-fewar7yl.entry.js
p-ieidis0g.entry.js
p-l3mq0mfk.entry.js
p-p56qico8.entry.js
p-pmvvzymqy.entry.js
p-u9ue1gt5.entry.js
p-vazvatcb.entry.js
p-vz1gegwx.entry.js
p-y8369yin.entry.js
p-zuxp3eca.entry.js.

Could you build a version of the microbit-web-bluetooth example with a single bundle.js file that would work as pure js? This would be handy for Android\IOS WebView developers. Is this possible or are there limitations I don't see?

**Comment by thegecko** [comment]
I'm not sure what you are asking for here.

Any library will have an output file you will need to include in your web page. CORS stops you from loading files from a different domain, so you just need the main file alongside your html.

You want to copy the `microbit.umd.js` file from `dist` and put it wherever you need it.

**Comment by VlasovAlexey** [comment]
Sorry for the stupid question. Got it. It's working. Thanks again for the great library.
