### ISSUE TITLE
ERR_FILE_NOT_FOUND: microbit.umd.js when using examples/index.html from this repository

### ISSUE THREAD

**Issue by ngammarano** [thegecko/microbit-web-bluetooth#8]
I understand that it is working on https://thegecko.github.io/microbit-web-bluetooth/examples/index.html.

Nevertheless, I think it would be good to remove `dist` from file `.gitignore`, and then add the file `/dist/microbit.umd.js` (which is in https://thegecko.github.io/microbit-web-bluetooth/dist/microbit.umd.js) to this repository.

**Comment by thegecko** [comment]
https://github.com/thegecko/microbit-web-bluetooth/blob/gh-pages/dist/microbit.umd.js

As that is a compiled output, it shouldn't really be added to SCM
