### ISSUE TITLE
Possible to use on Calliope Mini Icon?

### ISSUE THREAD

**Issue by avanderbergh** [thegecko/microbit-web-bluetooth#9]
Hi,

I would like to see if this package also works on the Calliope Mini Icon. From their documentation this should be possible.

"We place great emphasis on a maximum of compatibility to the British model - that's why it's possible to use existing code for the micro:bit on the mini as well." - calliope.cc/en/faq

However when I load the hex files onto the Calliope, it flashes "0 5  0 ☹️" on repeat.

Do you perhaps have the source of the hex files, so I could try and recompile for the Calliope?

**Comment by thegecko** [comment]
The examples are based on the source found at:

https://github.com/lancaster-university/microbit-samples

With a `config.json`:

```json
{
    "microbit-dal": {
        "bluetooth": {
            "enabled": 1,
            "pairing_mode": 1,
            "private_addressing": 0,
            "open": 1,
            "whitelist": 1,
            "advertising_timeout": 0,
            "tx_power": 0,
            "dfu_service": 0,
            "event_service": 1,
            "device_info_service": 1,
            "security_level": "SECURITY_MODE_ENCRYPTION_NO_MITM"
        },
        "gatt_table_size": "0x700"
    }
}
```
